name = "Colony Protocol: Influx"
author = "MichaelHeaton"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a64cbad25136752362d627cce2aff4401132ea96ac982b87bc84b41ebea058f5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = ["1.21"]
