name = "Colony Protocol: Influx"
author = "MichaelHeaton"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "580a7c642e634b3c2de37548eb2c2d1a4d1b682818eb963eac9086c91cb303ee"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
